# 1. Configuración de Base de Datos (NEON)
spring.datasource.url=jdbc:postgresql://ep-blue-cloud-anlolky8.c-6.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_9E5cPCgjSAwl
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Configuración de Seguridad (JWT) - CRÍTICO PARA QUE ARRANQUE
jwt.secret=esta_es_una_clave_secreta_muy_larga_para_que_el_sistema_no_tire_error_12345
